### ISSUE TITLE
URL can't contain control characters

### ISSUE THREAD

**Issue by Kyrremann** [nais/smsmanager#1]
Klarer ikke å sende sms for Canary-alert
```
[2020-06-30 12:27:33 +0000] [11] [ERROR] Exception in ASGI application
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/uvicorn/protocols/http/httptools_impl.py", line 385, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/usr/local/lib/python3.7/site-packages/uvicorn/middleware/proxy_headers.py", line 45, in __call__
    return await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/fastapi/applications.py", line 149, in __call__
    await super().__call__(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/applications.py", line 102, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc from None
  File "/usr/local/lib/python3.7/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 550, in __call__
    await route.handle(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 227, in handle
    await self.app(scope, receive, send)
  File "/usr/local/lib/python3.7/site-packages/starlette/routing.py", line 41, in app
    response = await func(request)
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 197, in app
    dependant=dependant, values=values, is_coroutine=is_coroutine
  File "/usr/local/lib/python3.7/site-packages/fastapi/routing.py", line 148, in run_endpoint_function
    return await dependant.call(**values)
  File "/app/main.py", line 43, in sms
    sendSMS(transformText(message), alert['annotations']['recipients'])
  File "/app/main.py", line 27, in sendSMS
    response = urllib.request.urlopen(url).read()
  File "/usr/local/lib/python3.7/urllib/request.py", line 222, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/local/lib/python3.7/urllib/request.py", line 525, in open
    response = self._open(req, data)
  File "/usr/local/lib/python3.7/urllib/request.py", line 543, in _open
    '_open', req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 503, in _call_chain
    result = func(*args)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1347, in http_open
    return self.do_open(http.client.HTTPConnection, req)
  File "/usr/local/lib/python3.7/urllib/request.py", line 1319, in do_open
    encode_chunked=req.has_header('Transfer-encoding'))
  File "/usr/local/lib/python3.7/http/client.py", line 1252, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "/usr/local/lib/python3.7/http/client.py", line 1263, in _send_request
    self.putrequest(method, url, **skips)
  File "/usr/local/lib/python3.7/http/client.py", line 1114, in putrequest
    self._validate_path(url)
  File "/usr/local/lib/python3.7/http/client.py", line 1205, in _validate_path
    raise InvalidURL(f"URL can't contain control characters. {url!r} "
http.client.InvalidURL: URL can't contain control characters. '/sms?recipients=***&message=[FIRING]%20Canary%20does%20not%20sing%20in%20prod-gcp%0aProblem%20with%20NAIS%20deploy\n\nCanary%20application%20should%20deploy%20every%205%20minutes,%20but%20has%20not%20been%20deployed%20successfully%20in%20over%2020%20minutes.\n\nConsequence:%20NAIS%20deploy%20is%20probably%20unavailable.%20Some%20or%20all%20users%20might%20not%20be%20able%20to%20deploy.\n&messageType=TEXT&LogDelivery=NO&username=***&password=***' (found at least '\n')
```

Slack-melding
```
Canary does not sing in prod-gcp
Problem with NAIS deploy
Canary application should deploy every 5 minutes, but has not been deployed successfully in over 20 minutes.
Consequence: NAIS deploy is probably unavailable. Some or all users might not be able to deploy.
```

**Comment by Kyrremann** [comment]
Alerten som definert i nais/nais-yaml
> Problem with NAIS deploy\n\nCanary application should deploy every 5 minutes, but has not been deployed successfully in over 20 minutes.\n\nConsequence: NAIS deploy is probably unavailable. Some or all users might not be able to deploy.\n

De forhåndsdefinerte `\n` feiler, så de må enten fjernes eller bare byttes til sms-linjeskift. Tenker sistnevnte er enklest.

**Comment by Kyrremann** [comment]
Fixed https://github.com/nais/smsmanager/commit/1a2e6cd7eb1487646cb011616ea804856c22a2c6
